<?php

namespace App\Enums;

enum ThreatTypeEnum: string
{
    case THREAT_TYPE_UNSPECIFIED = 'THREAT_TYPE_UNSPECIFIED';
    case MALWARE = 'MALWARE';
    case SOCIAL_ENGINEERING = 'SOCIAL_ENGINEERING';
    case UNWANTED_SOFTWARE = 'UNWANTED_SOFTWARE';
    case POTENTIALLY_HARMFUL_APPLICATION = 'POTENTIALLY_HARMFUL_APPLICATION';
}
